apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: virtual-router-controller-role
  namespace: virtual-router
rules:
- apiGroups:
  - "tmax.hypercloud.com"
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - "coordination.k8s.io"
  resources:
  - "leases"
  verbs:
  - '*'
- apiGroups:
  - "*"
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: virtual-router-controller-sa
  namespace: virtual-router
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: virtual-router-controller-rb
  namespace: virtual-router
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: virtual-router-controller-role
subjects:
- kind: ServiceAccount
  name: virtual-router-controller-sa
  namespace: virtual-router
---
apiVersion: v1
kind: Pod
metadata:
  name: controller
  namespace: virtual-router
  labels:
    app: controller
spec:
  nodeName: node01
  serviceAccount: virtual-router-controller-sa
  containers:
  - name: controller
    image: 192.168.7.191:5000/virtual-router:0.1
    imagePullPolicy: Always
    # args:
    # - "-lease-lock-name=controller-lease-lock"
    # - "-lease-lock-namespace=sample-controller"
    # env:
    # - name: VM_PROVIDER_SVC_NAME
    #   value: "vmprovider"
    # - name: VM_PROVIDER_SVC_NAMESPACE
    #   value: "sample-controller"
    # - name: VM_PROVIDER_PORT
    #   value: "8001"
    # - name: PROMETHEUS_EXPORTER_ADDRESS
    #   value: ":2112"
    # - name: CONTROLLER_NAMESPACE
    #   valueFrom:
    #     fieldRef:
    #       fieldPath: metadata.namespace
    # ports:
    # - name: prometheus
    #   containerPort: 2112
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: controller
#   namespace: sample-controller
#   labels:
#     app: controller
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       app: controller
#   template:
#     metadata:
#       namespace: sample-controller
#       labels:
#         app: controller
#     spec:
#       serviceAccount: vm-controller-sa
#       containers:
#       - name: controller
#         image: controller:0.1
#         args:
#         - "-lease-lock-name=controller-lease-lock"
#         - "-lease-lock-namespace=sample-controller"
#         env:
#         - name: VM_PROVIDER_SVC_NAME
#           value: "vmprovider"
#         - name: VM_PROVIDER_SVC_NAMESPACE
#           value: "sample-controller"
#         - name: VM_PROVIDER_PORT
#           value: "8001"
#         - name: PROMETHEUS_EXPORTER_ADDRESS
#           value: ":2112"
#         - name: CONTROLLER_NAMESPACE
#           valueFrom:
#             fieldRef:
#               fieldPath: metadata.namespace
#         ports:
#         - name: prometheus
#           containerPort: 2112