apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: virtualrouters.tmax.hypercloud.com
spec:
  group: tmax.hypercloud.com
  version: v1
  names:
    kind: VirtualRouter
    plural: virtualrouters
    shortNames: 
    - vr
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            vlanNumber:
              type: integer
            internalCIDR:
              type: string
            internalIPs:
              type: array
              items:
                type: string
            externalIPs:
              type: array
              items:
                type: string
            replicas:
              type: integer
              minimum: 1
              maximum: 10
