apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: virtualrouters.tmax.hypercloud.com
spec:
  group: tmax.hypercloud.com
  version: v1
  names:
    kind: VirtualRouter
    plural: virtualrouters
    shortNames: 
    - vr
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            vlanNumber:
              type: integer
            externalIP:
              type: string
            externalNetmask:
              type: string
            internalIP:
              type: string
            internalNetmask:
              type: string
            gatewayIP:
              type: string
            replicas:
              type: integer
              minimum: 1
              maximum: 10
            image:
              type: string
            nodeSelector:
              type: array
              items:
                type: object
                properties:
                  key:
                    type: string
                  value:
                    type: string
                required:
                - key
                - value
            affinity:
              type: object
              properties:
                nodeAffinity:
                  type: object
                  properties:
                    requiredDuringSchedulingIgnoredDuringExecution:
                      type: object
                      properties:
                        nodeSelectorTerms:
                          type: array
                          items:
                            type: object
                            properties:
                              matchExpressions:
                                type: array
                                items:
                                  type: object
                                  properties:
                                    key:
                                      type: string
                                    operator:
                                      type: string
                                    values:
                                      type: array
                                      items:
                                        type: string
                              matchFields:
                                type: array
                                items:
                                  type: object
                                  properties:
                                    key:
                                      type: string
                                    operator:
                                      type: string
                                    values:
                                      type: array
                                      items:
                                        type: string          
                    preferredDuringSchedulingIgnoredDuringExecution:
                      type: array
                      items:
                        type: object
                        properties:
                          weight:
                            type: integer
                          preference:
                            type: object
                            properties:
                              matchExpressions:
                                type: array
                                items:
                                  type: object
                                  properties:
                                    key:
                                      type: string
                                    operator:
                                      type: string
                                    values:
                                      type: array
                                      items:
                                        type: string  
                              matchFields:
                                type: array
                                items:
                                  type: object
                                  properties:
                                    key:
                                      type: string
                                    operator:
                                      type: string
                                    values:
                                      type: array
                                      items:
                                        type: string
          required:
          - replicas
          - image
